### PR TITLE
For privacy concerns, the spin bit may be disabled in specific use cases.

### PR DESCRIPTION
**Pull request by loganaden**

### CODE REVIEW

**Comment by loganaden** [comment]
ping

**Comment by britram** [comment]
pong, back from leave, looking at these drafts this week...

**Comment by britram** [comment]
The document definitely needs to be updated to reflect this decision from BKK (see #58), but I think the reasons here are more comprehensive than just proxies.

**Comment by loganaden** [comment]
Thank you for your feedback. I will update the proposed patch.

**Comment by britram** [comment]
AFAICT this has been overtaken by changes to the spin bit text in -transport as well as by #66

**Pull request closed without merging**
